/** @type {import('prettier').Config} */
module.exports = {
  endOfLine: "lf",
  semi: false,
  singleQuote: false,
  tabWidth: 2,
  trailingComma: "es5",
  importOrder: [
    "^(react/(.*)$)|^(react$)",
    "^(next/(.*)$)|^(next$)",
    "<THIRD_PARTY_MODULES>",
    "",
    "^@/src/types/(.*)$",
    "^@/src/lib/(.*)$",
    "^@/src/hooks/(.*)$",
    "^@/src/components/ui/(.*)$",
    "^@/src/components/(.*)$",
    "^@/src/styles/(.*)$",
    "^@/src/posts/(.*)$",
    "^@/src/utils/(.*)$",
    "^@/src/page/(.*)$",
    "",
    "^[./src/(.*)$]",
  ],
  importOrderSeparation: false,
  importOrderSortSpecifiers: true,
  importOrderBuiltinModulesToTop: true,
  importOrderParserPlugins: ["typescript", "jsx", "decorators-legacy"],
  importOrderMergeDuplicateImports: true,
  importOrderCombineTypeAndValueImports: true,
  plugins: ["@ianvs/prettier-plugin-sort-imports"],
}
